services:
  img-converter:
    image: ghcr.io/lc010224/img-converter:latest
    container_name: img-converter
    restart: unless-stopped
    ports:
      - "3115:7745"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/img-converter/data:/data
      - /home/img-converter/local-temp:/local-temp
