services:
  img-converter:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: img-converter
    restart: unless-stopped
    ports:
      - "3115:7745"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/img-converter/data:/data
